Error Step

diff --git a/.github/workflows/firstgithubworkflow.yaml b/.github/workflows/firstgithubworkflow.yaml
--- a/.github/workflows/firstgithubworkflow.yaml
+++ b/.github/workflows/firstgithubworkflow.yaml
@@ -28,4 +28,7 @@ jobs:
           run: |
             echo : "Hello from Windows"
             Write-Output "Hello from Rakesh"
-         
+        - name: Error Step
+          run: |
+            echo "This step will fail"
+            exit 1"
